name: Build & Deploy App
on:
  workflow_run:
    workflows: ["Yarn Check"]
    types: ["completed"]
    branches: [main]

jobs:
  build-deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - uses: actions/checkout@v3
      with:
        lfs: true
        submodules: 'recursive'

    - uses: actions/setup-node@v3
      with:
        node-version: lts/hydrogen

    - name: Build
      run: |
        yarn install --immutable | grep -v 'YN0013'
        yarn build

    - name: Deploy App
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./apps/main-app/dist

        # navigate into the build output directory
        # cd apps/main-app/dist

        # place .nojekyll to bypass Jekyll processing
        # echo > .nojekyll

        # git init
        # git checkout -B main
        # git add -A
        # git commit -m 'deploy'
        # git push -f git@github.com:jimmychu0807/combination-app.git main:gh-pages
